server:
  port: 8090
spring:
  mandatory-file-encoding: UTF-8
  data:
    mongodb:
      authentication-database: SpringMongoTest
      port: 27017
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB